/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * N-API.RS exported functions via macro
*/
export interface ArgsAudioToReSample {
  sampleRateInput: number
  sampleRateOutput: number
  channels: number
}
export interface ArgsAudioFile {
  argsAudioToReSample: ArgsAudioToReSample
  inputRawPath: string
  outputPath: string
}
export interface ArgsAudioBuffer {
  argsAudioToReSample: ArgsAudioToReSample
  inputBuffer: Buffer
}
export function reSampleBuffers(args: ArgsAudioBuffer): Int16Array
export interface ArgsAudioInt16Array {
  argsAudioToReSample: ArgsAudioToReSample
  inputInt16Array: Int16Array
}
export function reSampleInt16Array(args: ArgsAudioInt16Array): Int16Array
