/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function reSampleBuffers(inputBuffer: Buffer, inputSampleRate: number, outputSampleRate: number, channels: number): Buffer
