/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * N-API.RS exported functions via macro
*/
export interface ArgsAudioToReSample {
  sampleRateInput: number
  sampleRateOutput: number
  channels: number
}
export const enum DataType {
  I16 = 0,
  F32 = 1
}
export interface ArgsAudioFile {
  argsAudioToReSample: ArgsAudioToReSample
  inputRawPath: string
  outputPath: string
  typeOfBinData: DataType
}
export function reSampleAudioFile(args: ArgsAudioFile): void
export interface ArgsAudioBuffer {
  argsAudioToReSample: ArgsAudioToReSample
  inputBuffer: Buffer
}
export function reSampleBuffers(args: ArgsAudioBuffer): Buffer
export interface ArgsAudioInt16Buffer {
  argsAudioToReSample: ArgsAudioToReSample
  inputInt16Buffer: Buffer
}
export function reSampleInt16Buffer(args: ArgsAudioInt16Buffer): Buffer
